/* ============================================================
   PRODUCT DATA
   Central dataset for the entire store. Every page (home, shop,
   product, cart, wishlist, search) reads from this file.

   Every product below points to real photography in
   images/products/ or images/lifestyle/. No placeholder graphics
   remain in the catalog.
   ============================================================ */

const SITE_CONFIG = {
  brand: "Forme",
  currency: "$",
  freeShippingThreshold: 100,
  standardShipping: 10,
  expressShipping: 25,
  taxRate: 0.08,
  promoCodes: {
    "WELCOME10": 0.10,
    "FORME20": 0.20
  }
};

/*
  colors: [{ name, hex }] — reflects the color actually shown in the photo
  images: two entries where a second angle exists, otherwise the same
  file is used for both so the layout still works
*/
const PRODUCTS = [
  {
    id: "forme-001",
    name: "Tailored Tuxedo Suit Set",
    category: "Women",
    type: "Outerwear",
    price: 428,
    oldPrice: null,
    images: ["images/products/navy-tuxedo-suit-set.jpg", "images/products/navy-tuxedo-suit-set.jpg"],
    colors: [{ name: "Midnight Navy", hex: "#1B2434" }],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.9,
    reviewCount: 87,
    badge: "NEW",
    description: "A two piece tuxedo set cut from fine wool with a satin trimmed shawl collar. Sharp enough for black tie, versatile enough to wear the blazer and trouser separately.",
    details: ["Fine wool blend with satin trim", "Shawl collar blazer, straight leg trouser", "Fully lined blazer", "Dry clean only", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-002",
    name: "Statement Pantsuit",
    category: "Women",
    type: "Outerwear",
    price: 368,
    oldPrice: 420,
    images: ["images/products/red-pantsuit-set.jpg", "images/products/red-pantsuit-set.jpg"],
    colors: [{ name: "Deep Garnet", hex: "#7A2230" }],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviewCount: 63,
    badge: "SALE",
    description: "A collarless blazer and matching straight leg trouser in a rich garnet wool crepe, finished with a fine satin edge. Built to hold its own in a room.",
    details: ["Wool crepe with satin edging", "Collarless blazer, straight leg trouser", "Fully lined", "Dry clean only", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-003",
    name: "Tailored Skirt Suit with Trim",
    category: "Women",
    type: "Outerwear",
    price: 398,
    oldPrice: null,
    images: ["images/products/navy-trim-skirt-suit.jpg", "images/products/navy-trim-skirt-suit.jpg"],
    colors: [{ name: "Navy", hex: "#26344A" }],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 41,
    badge: null,
    description: "A structured blazer and pencil skirt in a textured navy weave, edged in a contrast leather trim. A power suit built for the room where decisions get made.",
    details: ["Textured wool blend with leather trim", "Structured blazer, pencil skirt", "Fully lined", "Dry clean only", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-004",
    name: "Beaded Tulle Evening Gown",
    category: "Women",
    type: "Dresses",
    price: 548,
    oldPrice: null,
    images: ["images/products/black-beaded-evening-gown.jpg", "images/products/black-beaded-evening-gown.jpg"],
    colors: [{ name: "Black", hex: "#141414" }],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviewCount: 29,
    badge: "LIMITED",
    description: "A full length gown in hand beaded tulle over a fitted lining, with sheer long sleeves and a dramatic train. Reserved for the nights that call for it.",
    details: ["Hand beaded tulle over fitted lining", "Sheer long sleeves, full train", "Concealed back zip", "Dry clean only", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 14 days of delivery, unworn and with tags attached, due to the nature of eveningwear."
  },
  {
    id: "forme-005",
    name: "Relaxed Linen Robe Jacket",
    category: "Women",
    type: "Shirts",
    price: 158,
    oldPrice: null,
    images: ["images/lifestyle/woman-robe-portrait.jpg", "images/lifestyle/woman-robe-portrait.jpg"],
    colors: [{ name: "Charcoal", hex: "#3E3B37" }],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviewCount: 74,
    badge: "BEST SELLER",
    description: "An open front robe jacket in washed linen, tied at the waist with a self fabric belt. Layers over almost anything and softens with every wash.",
    details: ["100% washed linen", "Open front, self tie belt", "Machine washable", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-006",
    name: "Ribbed Wool Cardigan",
    category: "Women",
    type: "Shirts",
    price: 148,
    oldPrice: null,
    images: ["images/lifestyle/model-walking-cardigan.jpg", "images/lifestyle/model-walking-cardigan.jpg"],
    colors: [{ name: "Rust", hex: "#B05C33" }],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    reviewCount: 112,
    badge: null,
    description: "A longline cardigan in a fine ribbed wool blend, easy to wear open over knitwear or buttoned through as a layering piece on cooler days.",
    details: ["Wool and acrylic blend rib knit", "Longline fit, button front", "Hand wash cold", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-007",
    name: "Double Breasted Wool Overcoat",
    category: "Men",
    type: "Outerwear",
    price: 348,
    oldPrice: null,
    images: ["images/products/grey-overcoat-duo.jpg", "images/products/grey-overcoat-duo.jpg"],
    colors: [{ name: "Grey Melange", hex: "#8A8781" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.9,
    reviewCount: 96,
    badge: "BEST SELLER",
    description: "A double breasted overcoat in a heavyweight wool melange, cut long with a wide peak lapel. The kind of coat that gets better with every winter.",
    details: ["Wool melange, heavyweight", "Double breasted, peak lapel", "Fully lined", "Dry clean only", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-008",
    name: "Three Piece Wool Suit",
    category: "Men",
    type: "Outerwear",
    price: 458,
    oldPrice: null,
    images: ["images/lifestyle/man-three-piece-suit-portrait.jpg", "images/lifestyle/man-three-piece-suit-portrait.jpg"],
    colors: [{ name: "Grey", hex: "#8C877E" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.8,
    reviewCount: 58,
    badge: "NEW",
    description: "A three piece suit in a fine wool weave, including a matching waistcoat for a finished silhouette without a jacket. Built for the days that call for a full suit.",
    details: ["Fine wool weave", "Blazer, waistcoat, and trouser", "Half canvas construction", "Dry clean only", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-009",
    name: "Unstructured Linen Blazer",
    category: "Men",
    type: "Outerwear",
    price: 228,
    oldPrice: 268,
    images: ["images/lifestyle/man-olive-blazer-portrait.jpg", "images/lifestyle/man-olive-blazer-portrait.jpg"],
    colors: [{ name: "Olive", hex: "#5C5B45" }],
    sizes: ["S", "M", "L", "XL", "XXL"],
    rating: 4.7,
    reviewCount: 84,
    badge: "SALE",
    description: "An unlined blazer in a soft linen weave, built without the stiffness of a traditional jacket. Wear it over a tee or a knit for a look that never tries too hard.",
    details: ["100% linen, unstructured", "Unlined, notch lapel", "Machine washable", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and with tags attached. See our Returns page for the full policy."
  },
  {
    id: "forme-010",
    name: "Cap Toe Lace Up Boot",
    category: "Men",
    type: "Shoes",
    price: 268,
    oldPrice: null,
    images: ["images/products/black-cap-toe-boots.jpg", "images/products/boot-heel-detail.jpg"],
    colors: [{ name: "Black", hex: "#161616" }],
    sizes: ["40", "41", "42", "43", "44", "45"],
    rating: 4.9,
    reviewCount: 118,
    badge: "BEST SELLER",
    description: "A cap toe boot in full grain leather on a lugged rubber sole, built to handle rougher ground without giving up a clean silhouette.",
    details: ["Full grain leather upper", "Lugged rubber sole", "Leather lining and footbed", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and in original box. See our Returns page for the full policy."
  },
  {
    id: "forme-011",
    name: "Buckle Strap Chelsea Boot",
    category: "Men",
    type: "Shoes",
    price: 248,
    oldPrice: null,
    images: ["images/products/black-chelsea-boots-buckle.jpg", "images/products/black-chelsea-boots-buckle.jpg"],
    colors: [{ name: "Black", hex: "#161616" }],
    sizes: ["40", "41", "42", "43", "44", "45"],
    rating: 4.8,
    reviewCount: 76,
    badge: "NEW",
    description: "A Chelsea boot in polished leather with a signature buckle strap detail across the ankle. Elastic side panels make it as easy to wear as a slip on.",
    details: ["Polished leather upper", "Elastic side panel, buckle strap detail", "Leather sole with rubber insert", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and in original box. See our Returns page for the full policy."
  },
  {
    id: "forme-012",
    name: "Classic Chelsea Boot",
    category: "Men",
    type: "Shoes",
    price: 218,
    oldPrice: null,
    images: ["images/products/black-chelsea-boots-plain-a.jpg", "images/products/black-chelsea-boots-plain-b.jpg"],
    colors: [{ name: "Black", hex: "#161616" }],
    sizes: ["40", "41", "42", "43", "44", "45"],
    rating: 4.8,
    reviewCount: 132,
    badge: null,
    description: "A pared back Chelsea boot in smooth leather, free of hardware and built to move from the office to the weekend without a second thought.",
    details: ["Smooth leather upper", "Elastic side panels", "Leather sole with rubber insert", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and in original box. See our Returns page for the full policy."
  },
  {
    id: "forme-013",
    name: "Tan Penny Loafer",
    category: "Men",
    type: "Shoes",
    price: 228,
    oldPrice: null,
    images: ["images/products/tan-penny-loafers.jpg", "images/products/loafer-detail.jpg"],
    colors: [{ name: "Tan", hex: "#A9713F" }],
    sizes: ["40", "41", "42", "43", "44", "45"],
    rating: 4.9,
    reviewCount: 145,
    badge: "BEST SELLER",
    description: "A penny loafer in burnished tan leather on a stacked wood look heel. Made to be worn without socks in summer and with wool trousers the rest of the year.",
    details: ["Burnished full grain leather", "Stacked heel with rubber sole", "Leather lining", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and in original box. See our Returns page for the full policy."
  },
  {
    id: "forme-014",
    name: "Suede Chukka Boot",
    category: "Men",
    type: "Shoes",
    price: 198,
    oldPrice: null,
    images: ["images/products/grey-suede-chukka-boots.jpg", "images/products/grey-suede-chukka-boots.jpg"],
    colors: [{ name: "Charcoal Suede", hex: "#454545" }],
    sizes: ["40", "41", "42", "43", "44", "45"],
    rating: 4.7,
    reviewCount: 69,
    badge: null,
    description: "A two eyelet chukka boot in soft suede on a lightweight sole. Casual enough for denim, clean enough to wear with tailoring on a Friday.",
    details: ["Suede upper", "Two eyelet lace closure", "Lightweight rubber sole", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and in original box. See our Returns page for the full policy."
  },
  {
    id: "forme-015",
    name: "Minimal Leather Sneaker",
    category: "Men",
    type: "Shoes",
    price: 178,
    oldPrice: 210,
    images: ["images/products/white-leather-sneakers.jpg", "images/products/white-leather-sneakers.jpg"],
    colors: [{ name: "White", hex: "#F5F5F3" }],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    rating: 4.8,
    reviewCount: 203,
    badge: "SALE",
    description: "A tonal white sneaker in smooth leather with a clean silhouette and minimal stitching. Built to stay sharp with a wipe down rather than a wash.",
    details: ["Smooth leather upper", "Rubber cupsole", "Breathable leather lining", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unworn and in original box. See our Returns page for the full policy."
  },
  {
    id: "forme-016",
    name: "Leather Weekend Duffel",
    category: "Accessories",
    type: "Accessories",
    price: 328,
    oldPrice: null,
    images: ["images/products/duffel-bag.jpg", "images/products/three-duffel-bags-group.jpg"],
    colors: [{ name: "Black", hex: "#161616" }],
    sizes: [],
    rating: 4.9,
    reviewCount: 91,
    badge: "BEST SELLER",
    description: "A weekend duffel in full grain leather with suede panel accents and a horsebit hardware detail. Sized to clear most airline carry on limits.",
    details: ["Full grain leather with suede panels", "Two exterior zip pockets", "Detachable shoulder strap", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unused and in original packaging. See our Returns page for the full policy."
  },
  {
    id: "forme-017",
    name: "Leather Laptop Backpack",
    category: "Accessories",
    type: "Accessories",
    price: 248,
    oldPrice: null,
    images: ["images/products/backpack.jpg", "images/products/backpack.jpg"],
    colors: [{ name: "Black", hex: "#161616" }],
    sizes: [],
    rating: 4.8,
    reviewCount: 104,
    badge: "NEW",
    description: "A minimal backpack in pebbled leather with a padded laptop compartment and a front zip pocket for anything you need within reach.",
    details: ["Pebbled leather", "Padded 15 inch laptop sleeve", "Adjustable padded straps", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unused and in original packaging. See our Returns page for the full policy."
  },
  {
    id: "forme-018",
    name: "Structured Leather Tote",
    category: "Accessories",
    type: "Accessories",
    price: 268,
    oldPrice: null,
    images: ["images/lifestyle/woman-orange-tote-scene.jpg", "images/lifestyle/woman-green-tote-scene.jpg"],
    colors: [{ name: "Cognac", hex: "#A9622E" }],
    sizes: [],
    rating: 4.8,
    reviewCount: 87,
    badge: null,
    description: "A structured tote in pebbled leather sized to carry the everyday essentials, with an interior pocket and a magnetic top closure to keep things in place.",
    details: ["Pebbled leather", "Interior zip pocket", "Magnetic top closure", "Made in Portugal"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unused and in original packaging. See our Returns page for the full policy."
  },
  {
    id: "forme-019",
    name: "Acetate Sunglasses",
    category: "Accessories",
    type: "Accessories",
    price: 168,
    oldPrice: null,
    images: ["images/products/black-sunglasses.jpg", "images/products/black-sunglasses.jpg"],
    colors: [{ name: "Black", hex: "#161616" }],
    sizes: [],
    rating: 4.7,
    reviewCount: 58,
    badge: null,
    description: "A square frame in hand polished acetate with polarized lenses. Sized to suit most face shapes without feeling oversized.",
    details: ["Hand polished acetate frame", "Polarized UV400 lenses", "Includes protective case", "Made in Italy"],
    shipping: "Standard delivery in 3 to 5 business days. Express delivery in 1 to 2 business days. Free standard shipping on orders over $100.",
    returns: "Returns accepted within 30 days of delivery, unused and in original packaging. See our Returns page for the full policy."
  }
];

/* Sample review text used to populate the product page review list */
const REVIEW_SAMPLES = [
  { name: "Sarah M.", rating: 5, text: "The quality is far beyond what I expected at this price. Fits true to size and the material feels substantial." },
  { name: "James K.", rating: 5, text: "Exactly as pictured. This has quickly become something I reach for every week." },
  { name: "Priya R.", rating: 4, text: "Beautiful piece and fast shipping. Only reason for four stars is I wish it came in more colors." },
  { name: "Michael T.", rating: 5, text: "Fast shipping and beautiful packaging. Will definitely be ordering again." },
  { name: "Jessica L.", rating: 5, text: "Absolutely love the quality. Worth every penny and holds up well after several wears." },
  { name: "Daniel O.", rating: 4, text: "Great fit and the material feels premium. Runs slightly large so consider sizing down." }
];

function getProductById(id){
  return PRODUCTS.find(p => p.id === id);
}

function getRelatedProducts(product, count = 4){
  return PRODUCTS.filter(p => p.category === product.category && p.id !== product.id).slice(0, count);
}
